### PR TITLE
Replacing email logic and notifications logic by signals

### PR DESCRIPTION
**Pull request by nelsongallardo**
## Purpose :muscle:
Remove email logic and instead use django signals to send an event every time we were going to send an email.
## Changes required (Database, config, etc)
Remove all SENDGRID related variables in local config files.
## Links :link:
https://docs.djangoproject.com/en/3.0/topics/signals/

### CODE REVIEW

**Review by cesaraugustogarcia — CHANGES_REQUESTED** [review]
I suspect you have forgotten to push some changes/commits. I do not see signals logic being added.
Also remember to remove sendgrid dependency from requirements and cleanup some files like https://github.com/piraidev/django-social-rest-api/blob/master/socialapp/settings.py

**Comment by nelsongallardo** [comment]
still work in progress, a few changes left

**Comment by cesaraugustogarcia** [comment]
Ok some questions:
  - Can you please point me where the signals are being received? I just see the dispatch of them.
  - I believe we used to have Notifications that were saved on DB. Now we are not going to persists this anymore? If so, shouldn't we also be removing that class from models? db migrations?

**Comment by nelsongallardo** [comment]
Great point regarding Notifications. I removed the model, the view, and all the references to them.

Ref Signals, the responsibility of consuming/receiving the signals will be on the developer/project using our app. On our documentation, we will specify what kind of signals are sent under which actions, so then the developer will decide whether they want to consume those signals or not.

**Review by cesaraugustogarcia — DISMISSED** [review]
LGTM 🎸

**Comment by cesaraugustogarcia** [comment]
Please do not forget to squash

**Review by cesaraugustogarcia — APPROVED** [review]

**Pull request merged**
